# Tests the backend

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '10.x'
  displayName: 'Install Node.js'
- task: PublishTestResults@2

- script: |
    npm install
    npm run test
  displayName: 'npm install and test'
