version: '3.1'
services:
  mongo:
    image: mongo:4.0.9
    ports:
    - "27017:27017"
    command: --smallfiles
  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
