services:
  core.infrastructure.repository.EndpointStatusRepository:
    class: ../repository/Endpoint/EndpointStatusMongoRepository

  core.infrastructure.repository.HealthCheckRepository:
    class: ../repository/HealthCheck/HealthCheckMongoRepository

  core.infrastructure.InProcessPubSub:
    class: ../event/InProcessPubSub

  core.infrastructure.PingHealthChecker:
    class: '../PingHealthChecker'

  core.usecase.PingAllEndpoints:
    class: '../../usecase/PingAllEndpoints'
    arguments: [
      "@core.infrastructure.repository.EndpointStatusRepository",
      "@core.infrastructure.PingHealthChecker",
      "@core.infrastructure.InProcessPubSub",
      "@core.infrastructure.repository.HealthCheckRepository"
    ]

  core.usecase.UpdateEndpointStatus:
    class: '../../usecase/UpdateEndpointStatus'
    arguments: [
      "@core.infrastructure.repository.EndpointStatusRepository",
      "@core.infrastructure.repository.HealthCheckRepository"
    ]

  core.usecase.FindEndpointsForUser:
    class: "../../usecase/FindEndpointsForUser"
    arguments: [
      "@core.infrastructure.repository.EndpointStatusRepository"
    ]

  app.configuration:
    class: ../configuration/Configuration
