services:
  core.infrastructure.repository.FireBaseConnection:
    factory:
      class: ../repository/Connection
      method: getConnection

  core.infrastructure.repository.EndpointStatusFirebaseRepository:
    class: ../repository/EndpointStatusFirebaseRepository
    arguments: [
      "@core.infrastructure.repository.FireBaseConnection"
    ]

  core.infrastructure.repository.EndpointUpdatedEventRepository:
    class: ../repository/EndpointUpdatedEventFirebaseRepository
    arguments: [
      "@core.infrastructure.repository.FireBaseConnection"
    ]

  core.infrastructure.PubSub:
    class: ../PubSub

  core.domain.service.SavePingResult:
    class: '../../domain/model/service/SavePingResult'
    arguments: [
      "@core.infrastructure.repository.EndpointStatusFirebaseRepository"
    ]
  
  core.infrastructure.PingService:
    class: '../PingServiceImpl'

  core.usecase.PingAllEndpoints:
    class: '../../domain/usecase/PingAllEndpoints'
    arguments: [
      "@core.infrastructure.repository.EndpointStatusFirebaseRepository",
      "@core.domain.service.SavePingResult",
      "@core.infrastructure.PingService",
      "@core.infrastructure.PubSub"
    ]

  core.usecase.SaveEndpointUpdatedEvent:
    class: "../../domain/usecase/SaveEndpointUpdatedEvent"
    arguments: [
      "@core.infrastructure.repository.EndpointUpdatedEventRepository"
    ]
