services:
  app.infrastructure.repository.FireBaseConnection:
    factory:
      class: ../repository/Connection
      method: getConnection

  app.domain.EndpointStatusRepository:
    class: ../repository/EndpointStatusFirebaseRepository
    arguments: [
      "@app.infrastructure.repository.FireBaseConnection"
    ]

  app.infrastructure.repository.EndpointUpdatedEventRepository:
    class: ../repository/EndpointUpdatedEventFirebaseRepository
    arguments: [
      "@app.infrastructure.repository.FireBaseConnection"
    ]

  app.domain.PubSub:
    class: ../PubSub

  app.domain.service.SavePingResult:
    class: '../../domain/service/SavePingResult'
    arguments: [
      "@app.domain.EndpointStatusRepository"
    ]
  
  app.domain.service.PingService:
    class: '../PingServiceImpl'

  app.usecase.PingAllEndpoints:
    class: '../../usecase/PingAllEndpoints'
    arguments: [
      "@app.domain.EndpointStatusRepository",
      "@app.domain.service.SavePingResult",
      "@app.domain.service.PingService",
      "@app.domain.PubSub"
    ]

  app.usecase.SaveEndpointUpdatedEvent:
    class: "../../usecase/SaveEndpointUpdatedEvent"
    arguments: [
      "@app.infrastructure.repository.EndpointUpdatedEventRepository"
    ]
