services:
  core.infrastructure.repository.FireBaseConnection:
    factory:
      class: ../repository/Connection
      method: getConnection

  core.infrastructure.repository.EndpointStatusRepository:
    class: ../Endpoint/EndpointStatusMongoRepository

  core.infrastructure.repository.HealthCheckRepository:
    class: ../HealthCheck/HealthCheckMongoRepository

  core.infrastructure.PubSub:
    class: ../PubSub
  
  core.infrastructure.PingService:
    class: '../PingService'

  core.usecase.PingAllEndpoints:
    class: '../../usecase/PingAllEndpoints'
    arguments: [
      "@core.infrastructure.repository.EndpointStatusRepository",
      "@core.infrastructure.PingService",
      "@core.infrastructure.PubSub"
    ]

  core.usecase.SaveHealthCheck:
    class: "../../usecase/SaveHealthCheck"
    arguments: [
      "@core.infrastructure.repository.HealthCheckRepository"
    ]
